name: End-to-end Gen AI starter kit - Unit test

on:
  push:
    paths:
      - "gemini/sample-apps/e2e-gen-ai-app-starter-pack/**"
  pull_request:
    paths:
      - "gemini/sample-apps/e2e-gen-ai-app-starter-pack/**"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gemini/sample-apps/e2e-gen-ai-app-starter-pack
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry and dependencies
        run: |
          pip install poetry==1.8.3 --user
          python -m poetry install
      - name: Run tests
        run: |
          poetry run pytest tests/unit
